


import { IProduct } from "../redux/slices/collection/collection.type";

export const productsData: IProduct = {
  pagenumber: 2,
  productdto: [
    {
      id: 1,
      productName: "Howlite Faceted Turquoise Bracelet",
      offer: 50,
      imageUrl:
        "https://www.alamodelabel.in/cdn/shop/files/image_40f60237-a563-4afe-9120-10db13f9b7d9_800x.jpg?v=1689766628",
      phone: "admin@nazca.in",
      date: "2022-05-15",
      description:
        "Howlite & Turquoise Faceted bracelet will only bring you benefits as well as fulfilment. Turquoise dissipates negative disorders and helps to develop personal growth. It is also the stone of lovers as it nourishes romance and love. Howlite is a stone that",
      description1:
        "Wear this Howlite Faceted Turquoise bracelet to decrease your negative thoughts. These stones are known for their wisdom, promote personal growth, confidence, positive aura around you. These two stones are considered the best to calm the mind.",
      minQty: 1,
      deliveryTime: null,
      sizeChart: null,
      brand: "nike",
      relative: null,
      modify: "2024-03-16T09:21:42.848891",
      keyword: null,
      twitter: null,
      facebook: null,
      instagram: null,
      linkedin: null,
      pinterest: null,
      collectionNames: "Winter,Feature",
      vendorname: "SYSTEM",
      sku: "PHN",
      status: "Y",
      sizes: [
        {
          sid: 1,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-S",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 2,
          psize: "S",
          price: 2658.0,
          sku: "OMJB001-M",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 3,
          psize: "S",
          price: 2659.0,
          sku: "OMJB001-XL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 4,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-XXL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
      ],
      images: [
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-2.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-3.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
      ],
      price: 10,
      productcolor: "White,Turquoise",
      specification: "Stone:Howlite,Weight:10,Height:8,Width:1",
    },
    {
      id: 2,
      productName: "Howlite Faceted Turquoise Bracelet",
      offer: 50,
      imageUrl:
        "https://www.alamodelabel.in/cdn/shop/files/image_40f60237-a563-4afe-9120-10db13f9b7d9_800x.jpg?v=1689766628",
      phone: "admin@nazca.in",
      date: "2022-05-15",
      description:
        "Howlite & Turquoise Faceted bracelet will only bring you benefits as well as fulfilment. Turquoise dissipates negative disorders and helps to develop personal growth. It is also the stone of lovers as it nourishes romance and love. Howlite is a stone that",
      description1:
        "Wear this Howlite Faceted Turquoise bracelet to decrease your negative thoughts. These stones are known for their wisdom, promote personal growth, confidence, positive aura around you. These two stones are considered the best to calm the mind.",
      minQty: 1,
      deliveryTime: null,
      sizeChart: null,
      brand: "nike",
      relative: null,
      modify: "2024-03-16T09:21:42.848891",
      keyword: null,
      twitter: null,
      facebook: null,
      instagram: null,
      linkedin: null,
      pinterest: null,
      collectionNames: "Winter,Feature",
      vendorname: "SYSTEM",
      sku: "PHN",
      status: "Y",
      sizes: [
        {
          sid: 1,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-S",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 2,
          psize: "S",
          price: 2658.0,
          sku: "OMJB001-M",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 3,
          psize: "S",
          price: 2659.0,
          sku: "OMJB001-XL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 4,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-XXL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
      ],
      images: [
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-2.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-3.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
      ],
      price: 10,
      productcolor: "White,Turquoise",
      specification: "Stone:Howlite,Weight:10,Height:8,Width:1",
    },
    {
      id: 3,
      productName: "Howlite Faceted Turquoise Bracelet",
      offer: 50,
      imageUrl:
        "https://www.alamodelabel.in/cdn/shop/files/image_40f60237-a563-4afe-9120-10db13f9b7d9_800x.jpg?v=1689766628",
      phone: "admin@nazca.in",
      date: "2022-05-15",
      description:
        "Howlite & Turquoise Faceted bracelet will only bring you benefits as well as fulfilment. Turquoise dissipates negative disorders and helps to develop personal growth. It is also the stone of lovers as it nourishes romance and love. Howlite is a stone that",
      description1:
        "Wear this Howlite Faceted Turquoise bracelet to decrease your negative thoughts. These stones are known for their wisdom, promote personal growth, confidence, positive aura around you. These two stones are considered the best to calm the mind.",
      minQty: 1,
      deliveryTime: null,
      sizeChart: null,
      brand: "nike",
      relative: null,
      modify: "2024-03-16T09:21:42.848891",
      keyword: null,
      twitter: null,
      facebook: null,
      instagram: null,
      linkedin: null,
      pinterest: null,
      collectionNames: "Winter,Feature",
      vendorname: "SYSTEM",
      sku: "PHN",
      status: "Y",
      sizes: [
        {
          sid: 1,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-S",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 2,
          psize: "S",
          price: 2658.0,
          sku: "OMJB001-M",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 3,
          psize: "S",
          price: 2659.0,
          sku: "OMJB001-XL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 4,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-XXL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
      ],
      images: [
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-2.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-3.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
      ],
      price: 10,
      productcolor: "White,Turquoise",
      specification: "Stone:Howlite,Weight:10,Height:8,Width:1",
    },
    {
      id: 4,
      productName: "Howlite Faceted Turquoise Bracelet",
      offer: 50,
      imageUrl:
        "https://www.alamodelabel.in/cdn/shop/files/image_40f60237-a563-4afe-9120-10db13f9b7d9_800x.jpg?v=1689766628",
      phone: "admin@nazca.in",
      date: "2022-05-15",
      description:
        "Howlite & Turquoise Faceted bracelet will only bring you benefits as well as fulfilment. Turquoise dissipates negative disorders and helps to develop personal growth. It is also the stone of lovers as it nourishes romance and love. Howlite is a stone that",
      description1:
        "Wear this Howlite Faceted Turquoise bracelet to decrease your negative thoughts. These stones are known for their wisdom, promote personal growth, confidence, positive aura around you. These two stones are considered the best to calm the mind.",
      minQty: 1,
      deliveryTime: null,
      sizeChart: null,
      brand: "nike",
      relative: null,
      modify: "2024-03-16T09:21:42.848891",
      keyword: null,
      twitter: null,
      facebook: null,
      instagram: null,
      linkedin: null,
      pinterest: null,
      collectionNames: "Winter,Feature",
      vendorname: "SYSTEM",
      sku: "PHN",
      status: "Y",
      sizes: [
        {
          sid: 1,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-S",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 2,
          psize: "S",
          price: 2658.0,
          sku: "OMJB001-M",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 3,
          psize: "S",
          price: 2659.0,
          sku: "OMJB001-XL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 4,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-XXL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
      ],
      images: [
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-2.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-3.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
      ],
      price: 10,
      productcolor: "White,Turquoise",
      specification: "Stone:Howlite,Weight:10,Height:8,Width:1",
    },
    {
      id: 5,
      productName: "Howlite Faceted Turquoise Bracelet",
      offer: 50,
      imageUrl:
        "https://www.alamodelabel.in/cdn/shop/files/image_40f60237-a563-4afe-9120-10db13f9b7d9_800x.jpg?v=1689766628",
      phone: "admin@nazca.in",
      date: "2022-05-15",
      description:
        "Howlite & Turquoise Faceted bracelet will only bring you benefits as well as fulfilment. Turquoise dissipates negative disorders and helps to develop personal growth. It is also the stone of lovers as it nourishes romance and love. Howlite is a stone that",
      description1:
        "Wear this Howlite Faceted Turquoise bracelet to decrease your negative thoughts. These stones are known for their wisdom, promote personal growth, confidence, positive aura around you. These two stones are considered the best to calm the mind.",
      minQty: 1,
      deliveryTime: null,
      sizeChart: null,
      brand: "nike",
      relative: null,
      modify: "2024-03-16T09:21:42.848891",
      keyword: null,
      twitter: null,
      facebook: null,
      instagram: null,
      linkedin: null,
      pinterest: null,
      collectionNames: "Winter,Feature",
      vendorname: "SYSTEM",
      sku: "PHN",
      status: "Y",
      sizes: [
        {
          sid: 1,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-S",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 2,
          psize: "S",
          price: 2658.0,
          sku: "OMJB001-M",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 3,
          psize: "S",
          price: 2659.0,
          sku: "OMJB001-XL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 4,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-XXL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
      ],
      images: [
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-2.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-3.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
      ],
      price: 10,
      productcolor: "White,Turquoise",
      specification: "Stone:Howlite,Weight:10,Height:8,Width:1",
    },
    {
      id: 6,
      productName: "Howlite Faceted Turquoise Bracelet",
      offer: 50,
      imageUrl:
        "https://www.alamodelabel.in/cdn/shop/files/image_40f60237-a563-4afe-9120-10db13f9b7d9_800x.jpg?v=1689766628",
      phone: "admin@nazca.in",
      date: "2022-05-15",
      description:
        "Howlite & Turquoise Faceted bracelet will only bring you benefits as well as fulfilment. Turquoise dissipates negative disorders and helps to develop personal growth. It is also the stone of lovers as it nourishes romance and love. Howlite is a stone that",
      description1:
        "Wear this Howlite Faceted Turquoise bracelet to decrease your negative thoughts. These stones are known for their wisdom, promote personal growth, confidence, positive aura around you. These two stones are considered the best to calm the mind.",
      minQty: 1,
      deliveryTime: null,
      sizeChart: null,
      brand: "nike",
      relative: null,
      modify: "2024-03-16T09:21:42.848891",
      keyword: null,
      twitter: null,
      facebook: null,
      instagram: null,
      linkedin: null,
      pinterest: null,
      collectionNames: "Winter,Feature",
      vendorname: "SYSTEM",
      sku: "PHN",
      status: "Y",
      sizes: [
        {
          sid: 1,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-S",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 2,
          psize: "S",
          price: 2658.0,
          sku: "OMJB001-M",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 3,
          psize: "S",
          price: 2659.0,
          sku: "OMJB001-XL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 4,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-XXL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
      ],
      images: [
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-2.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-3.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
      ],
      price: 10,
      productcolor: "White,Turquoise",
      specification: "Stone:Howlite,Weight:10,Height:8,Width:1",
    },
    {
      id: 7,
      productName: "Howlite Faceted Turquoise Bracelet",
      offer: 50,
      imageUrl:
        "https://www.alamodelabel.in/cdn/shop/files/image_40f60237-a563-4afe-9120-10db13f9b7d9_800x.jpg?v=1689766628",
      phone: "admin@nazca.in",
      date: "2022-05-15",
      description:
        "Howlite & Turquoise Faceted bracelet will only bring you benefits as well as fulfilment. Turquoise dissipates negative disorders and helps to develop personal growth. It is also the stone of lovers as it nourishes romance and love. Howlite is a stone that",
      description1:
        "Wear this Howlite Faceted Turquoise bracelet to decrease your negative thoughts. These stones are known for their wisdom, promote personal growth, confidence, positive aura around you. These two stones are considered the best to calm the mind.",
      minQty: 1,
      deliveryTime: null,
      sizeChart: null,
      brand: "nike",
      relative: null,
      modify: "2024-03-16T09:21:42.848891",
      keyword: null,
      twitter: null,
      facebook: null,
      instagram: null,
      linkedin: null,
      pinterest: null,
      collectionNames: "Winter,Feature",
      vendorname: "SYSTEM",
      sku: "PHN",
      status: "Y",
      sizes: [
        {
          sid: 1,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-S",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 2,
          psize: "S",
          price: 2658.0,
          sku: "OMJB001-M",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 3,
          psize: "S",
          price: 2659.0,
          sku: "OMJB001-XL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 4,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-XXL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
      ],
      images: [
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-2.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-3.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
      ],
      price: 10,
      productcolor: "White,Turquoise",
      specification: "Stone:Howlite,Weight:10,Height:8,Width:1",
    },
    {
      id: 8,
      productName: "Howlite Faceted Turquoise Bracelet",
      offer: 50,
      imageUrl:
        "https://www.alamodelabel.in/cdn/shop/files/image_40f60237-a563-4afe-9120-10db13f9b7d9_800x.jpg?v=1689766628",
      phone: "admin@nazca.in",
      date: "2022-05-15",
      description:
        "Howlite & Turquoise Faceted bracelet will only bring you benefits as well as fulfilment. Turquoise dissipates negative disorders and helps to develop personal growth. It is also the stone of lovers as it nourishes romance and love. Howlite is a stone that",
      description1:
        "Wear this Howlite Faceted Turquoise bracelet to decrease your negative thoughts. These stones are known for their wisdom, promote personal growth, confidence, positive aura around you. These two stones are considered the best to calm the mind.",
      minQty: 1,
      deliveryTime: null,
      sizeChart: null,
      brand: "nike",
      relative: null,
      modify: "2024-03-16T09:21:42.848891",
      keyword: null,
      twitter: null,
      facebook: null,
      instagram: null,
      linkedin: null,
      pinterest: null,
      collectionNames: "Winter,Feature",
      vendorname: "SYSTEM",
      sku: "PHN",
      status: "Y",
      sizes: [
        {
          sid: 1,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-S",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 2,
          psize: "S",
          price: 2658.0,
          sku: "OMJB001-M",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 3,
          psize: "S",
          price: 2659.0,
          sku: "OMJB001-XL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
        {
          sid: 4,
          psize: "S",
          price: 2657.0,
          sku: "OMJB001-XXL",
          qty: 10,
          length: 0.0,
          width: 0.0,
          height: 0.0,
        },
      ],
      images: [
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-2.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-3.jpg",
        "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
      ],
      price: 10,
      productcolor: "White,Turquoise",
      specification: "Stone:Howlite,Weight:10,Height:8,Width:1",
    },
  ],
};
